server:
  port: 8080

default_server: '1.1.1.1:80'

routes:
  users:
    endpoints: ['1.1.1.1:80', '1.2.1.1:80']

  test:
    endpoints: ['1.1.1.2:80', '1.2.1.1:80']

  test/best:
    endpoints: ['1.1.1.3:80', '1.2.1.1:80']
