server:
  port: 8080

default_server: '127.0.0.1:3000'

auth:
  method:
    !jwt
      secret: "wdauhwaiuyhdbuadbauwbdaudgbaydutwvawdyutvy"

rate_limit:
  max_tokens: 50

routes:
  /users:
    endpoints: ['127.0.0.1:3001', '127.0.0.1:3002']
    needs_auth: true

  /test:
    endpoints: ['127.0.0.1:3003', '127.0.0.1:3004']

  /test/best:
    endpoints: ['127.0.0.1:3005', '127.0.0.1:3006']
    token_weight: 25

  /_static:
    endpoints: ['127.0.0.1:3004']
    is_static: true
