server:
  port: 8080

default_server: '1.1.1.1'

routes:
  users: 
    endpoints: ['1.1.1.1', '1.2.1.1']

  test:
    endpoints: ['1.1.1.2', '1.2.1.1']

  test/best:
    endpoints: ['1.1.1.3', '1.2.1.1']
