server:
  port: 8080

routes:
  - path: 'users'
    endpoints: ['1.1.1.1', '1.2.1.1']

  - path: 'test'
    endpoints: ['1.1.1.2', '1.2.1.1']

  - path: 'test/best'
    endpoints: ['1.1.1.3', '1.2.1.1']
