server:
  port: 8080

default_server: '127.0.0.1:3000'

routes:
  /users:
    endpoints: ['127.0.0.1:3001', '127.0.0.1:3002']

  /test:
    endpoints: ['127.0.0.1:3003', '127.0.0.1:3004']

  /test/best:
    endpoints: ['127.0.0.1:3005', '127.0.0.1:3006']
